version: '3.8'
services:
  redis:
    image: sloopstash/redis:v${AIA_REDIS_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data:/opt/redis/data
      - redis-log:/opt/redis/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${AIA_REDIS_VERSION}/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${AIA_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/server.conf
    networks:
      common:
        ipv4_address: ${AIA_REDIS_IP}
  chroma:
    image: sloopstash/chroma:v${AIA_CHROMA_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - chroma-data:/opt/chroma/data
      - chroma-log:/opt/chroma/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/chroma/${AIA_CHROMA_VERSION}/conf/supervisor.ini:/opt/chroma/system/supervisor.ini
      - ${HOME_DIR}/workload/chroma/${AIA_CHROMA_VERSION}/conf/server.conf:/opt/chroma/conf/server.conf
    networks:
      common:
        ipv4_address: ${AIA_CHROMA_IP}
  ollama:
    image: sloopstash/ollama:v${AIA_OLLAMA_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - ollama-model:/opt/ollama/model
      - ollama-data:/opt/ollama/data
      - ollama-log:/opt/ollama/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/ollama/${AIA_OLLAMA_VERSION}/conf/supervisor.ini:/opt/ollama/system/supervisor.ini
    networks:
      common:
        ipv4_address: ${AIA_OLLAMA_IP}
  app:
    image: sloopstash/python:v${AIA_PYTHON_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    environment:
      - STATIC_ENDPOINT=app-static.aia.${EXTERNAL_DOMAIN}:${AIA_NGINX_PORT}
    volumes:
      - ${AIA_APP_SOURCE}:/opt/app/source
      - app-log:/opt/app/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/_stack/fullstack/aia/app/conf/supervisor.ini:/opt/app/system/supervisor.ini
    depends_on:
      - redis
      - chroma
      - ollama
    networks:
      common:
        ipv4_address: ${AIA_APP_IP}
  nginx:
    image: sloopstash/nginx:v${AIA_NGINX_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    ports:
      - "${AIA_NGINX_PORT}:80"
    volumes:
      - ${AIA_APP_SOURCE}:/opt/app/source
      - nginx-log:/opt/nginx/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/nginx/${AIA_NGINX_VERSION}/conf/supervisor.ini:/opt/nginx/system/supervisor.ini
      - ${HOME_DIR}/workload/nginx/${AIA_NGINX_VERSION}/conf/server.conf:/opt/nginx/conf/server.conf
      - ${HOME_DIR}/_stack/fullstack/aia/nginx/conf/app.conf:/opt/nginx/conf/app.conf
    depends_on:
      - app
    networks:
      common:
        ipv4_address: ${AIA_NGINX_IP}
volumes:
  redis-data:
    driver: local
  redis-log:
    driver: local
  chroma-data:
    driver: local
  chroma-log:
    driver: local
  ollama-model:
    driver: local
  ollama-data:
    driver: local
  ollama-log:
    driver: local
  app-log:
    driver: local
  nginx-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${AIA_NETWORK}
