# MySQL Server configuration

[mysqld]

# Run the MySQL server as this operating system user.
user=mysql

# Data directory where database files are stored.
datadir=/opt/mysql/data

# PID file containing the MySQL server process ID.
pid-file=/opt/mysql/system/server.pid

# Socket file used for local client connections.
socket=/opt/mysql/system/mysql.sock

# Network settings.
port=5000
bind-address=0.0.0.0

# Logging
log-error=/opt/mysql/log/error.log
general_log=ON
general_log_file=/opt/mysql/log/general.log
slow_query_log=ON
slow_query_log_file=/opt/mysql/log/slow-query.log

# SQL mode to enforce stricter SQL behavior.
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES