version: '3.8'
services:
  ollama-deepseek-r1_1.5b:
    image: sloopstash/ollama:v${AI_OLLAMA_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - sloopstash-ollama-deepseek-r1_1.5b-data:/root/.ollama
      - sloopstash-ollama-deepseek-r1_1.5b-log:/opt/ollama/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/ollama/${AI_OLLAMA_VERSION}/conf/supervisor.ini:/opt/ollama/system/supervisor.ini
    networks:
      - common
    ports :
      - ${AI_OLLAMA_DEEPSEEK_PORT}:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
  ollama-deepseek-coder_1.3b:
    image: sloopstash/ollama:v${AI_OLLAMA_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - sloopstash-ollama-deepseek-coder_1.3b-data:/root/.ollama
      - sloopstash-ollama-deepseek-coder_1.3b-log:/opt/ollama/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/ollama/${AI_OLLAMA_VERSION}/conf/supervisor.ini:/opt/ollama/system/supervisor.ini
    networks:
      - common
    ports :
      - ${AI_OLLAMA_DEEPSEEK_CODER_PORT}:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama-deepseek-r1_1.5b
      - ollama-deepseek-coder_1.3b
    ports:
      - ${AI_OPEN_WEB_UI_DEEPSEEK_PORT}:8080
    environment:
      - "OLLAMA_BASE_URLS=http://ollama-deepseek-r1_1.5b:11434;http://ollama-deepseek-coder_1.3b:11434"
      - WEBUI_SECRET_KEY=
      - DEFAULT_MODELS=deepseek-r1:1.5b,deepseek-coder:1.3b
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - common
volumes:
  sloopstash-ollama-deepseek-r1_1.5b-data:
    driver: local
  sloopstash-ollama-deepseek-r1_1.5b-log:
    driver: local
  sloopstash-ollama-deepseek-coder_1.3b-data:
    driver: local
  sloopstash-ollama-deepseek-coder_1.3b-log:
    driver: local
  open-webui:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${AI_OLLAMA_DEEPSEEK_NETWORK}
