version: '3.8'
services:
  mongo-db-1:
    image: sloopstash/mongo-db:v${DATA_LAKE_MONGO_DB_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-1-data:/opt/mongo-db/data
      - mongo-db-1-log:/opt/mongo-db/log
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/script:/opt/mongo-db/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/conf/supervisor.ini:/opt/mongo-db/system/supervisor.ini
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/conf/server.conf:/opt/mongo-db/conf/server.conf
    networks:
      - common
  mongo-db-2:
    image: sloopstash/mongo-db:v${DATA_LAKE_MONGO_DB_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-2-data:/opt/mongo-db/data
      - mongo-db-2-log:/opt/mongo-db/log
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/script:/opt/mongo-db/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/conf/supervisor.ini:/opt/mongo-db/system/supervisor.ini
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/conf/server.conf:/opt/mongo-db/conf/server.conf
    depends_on:
      - mongo-db-1
    networks:
      - common
  mongo-db-3:
    image: sloopstash/mongo-db:v${DATA_LAKE_MONGO_DB_VERSION}
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-3-data:/opt/mongo-db/data
      - mongo-db-3-log:/opt/mongo-db/log
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/script:/opt/mongo-db/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/conf/supervisor.ini:/opt/mongo-db/system/supervisor.ini
      - ${HOME_DIR}/workload/mongo-db/${DATA_LAKE_MONGO_DB_VERSION}/replica-cluster/conf/server.conf:/opt/mongo-db/conf/server.conf
    depends_on:
      - mongo-db-1
    networks:
      - common
volumes:
  mongo-db-1-data:
    driver: local
  mongo-db-1-log:
    driver: local
  mongo-db-2-data:
    driver: local
  mongo-db-2-log:
    driver: local
  mongo-db-3-data:
    driver: local
  mongo-db-3-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DATA_LAKE_MONGO_DB_NETWORK}
