version: '3.8'
services:
  redis-1:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-1-data:/opt/redis/data
      - redis-1-log:/opt/redis/log
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/script:/opt/redis/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/server.conf:/opt/redis/conf/server.conf
    # depends_on:
    #   - redis-1
    networks:
      - common
  redis-2:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-2-data:/opt/redis/data
      - redis-2-log:/opt/redis/log
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/script:/opt/redis/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/server.conf:/opt/redis/conf/server.conf
    depends_on:
      - redis-1
    networks:
      - common
  redis-3:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-3-data:/opt/redis/data
      - redis-3-log:/opt/redis/log
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/script:/opt/redis/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/server.conf:/opt/redis/conf/server.conf
    depends_on:
      - redis-1
    networks:
      - common
  redis-4:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-4-data:/opt/redis/data
      - redis-4-log:/opt/redis/log
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/script:/opt/redis/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/server.conf:/opt/redis/conf/server.conf
    depends_on:
      - redis-1
    networks:
      - common
  redis-5:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-5-data:/opt/redis/data
      - redis-5-log:/opt/redis/log
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/script:/opt/redis/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/server.conf:/opt/redis/conf/server.conf
    depends_on:
      - redis-1
    networks:
      - common
  redis-6:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-6-data:/opt/redis/data
      - redis-6-log:/opt/redis/log
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/script:/opt/redis/script
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${DATA_LAKE_REDIS_VERSION}/cluster/conf/server.conf:/opt/redis/conf/server.conf
    depends_on:
      - redis-1
    networks:
      - common
volumes:
  redis-1-data:
    driver: local
  redis-1-log:
    driver: local
  redis-2-data:
    driver: local
  redis-2-log:
    driver: local
  redis-3-data:
    driver: local
  redis-3-log:
    driver: local
  redis-4-data:
    driver: local
  redis-4-log:
    driver: local
  redis-5-data:
    driver: local
  redis-5-log:
    driver: local
  redis-6-data:
    driver: local
  redis-6-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DATA_LAKE_REDIS_NETWORK}
