server {
  server_name app.cms.sloopstash.*;

  root /opt/app/source/web;
  index index.php;

  sendfile off;

  server_tokens off;

  error_log /opt/nginx/log/error.log warn;
  access_log /opt/nginx/log/access.log;

  large_client_header_buffers 4 16k;

  location / {
    try_files $uri /index.php?$query_string;
  }

  location ~ \.php$ {
    include /etc/nginx/fastcgi_params;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;

    fastcgi_pass app:9000;
  }

  location = /favicon.ico {
    return 204;
    access_log off;
    log_not_found off;
  }

  location ~ /\. {
    deny all;
  }

  location ~ ^/sites/.*/private {
    deny all;
  }

  location ~* \.(yml|yaml|twig|theme|module|install|inc|profile|test|info)$ {
    deny all;
  }
}
