input {
  beats {
    port => 5044
  }
}

filter {
  if [event][module] == "nginx" {
    if [fileset][name] == "access" {
      grok {
        match => {
          "message" => "\[%{HTTPDATE:[nginx][access][datetime]}\] %{IP:[nginx][access][remote_ip]} %{HOSTNAME:[nginx][access][host]} \"%{WORD:[nginx][access][method]} %{URIPATHPARAM:[nginx][access][path]} HTTP/%{NUMBER:[nginx][access][version]}\" %{NUMBER:[nginx][access][status]} \"%{DATA:[nginx][access][referer]}\" %{INT:[nginx][access][body_sent][bytes]} \"%{DATA:[nginx][access][user_agent]}\" %{NUMBER:[nginx][access][request_time]}"
        }
      }
      mutate {
        remove_field => ["message"]
      }
      date {
        match => [ "[nginx][access][datetime]", "dd/MMM/yyyy:HH:mm:ss Z" ]
        target => "@timestamp"
      }
      mutate {
        remove_field => ["[nginx][access][datetime]"]
      }
    }
    else if [fileset][name] == "error" {
      grok {
        match => {
          "message" => "%{DATE:[nginx][error][date]} %{TIME:[nginx][error][time]} \[%{WORD:[nginx][error][level]}\] %{INT:[nginx][error][process_id]}#%{INT:[nginx][error][thread_id]}: \*%{INT:[nginx][error][connection_id]} %{GREEDYDATA:[nginx][error][message]}"
        }
      }
      mutate {
        add_field => { "[nginx][error][datetime]" => "%{[nginx][error][date]} %{[nginx][error][time]} +0530" }
        remove_field => ["message", "[nginx][error][date]", "[nginx][error][time]"]
      }
      date {
        match => [ "[nginx][error][datetime]", "yy/MM/dd HH:mm:ss Z" ]
        target => "@timestamp"
      }
      mutate {
        remove_field => ["[nginx][error][datetime]"]
      }
    }
  }
  else if [event][module] == "docker" {
    if [fileset][name] == "log" {
      json {
        source => "message"
        target => "docker_json"
      }
      grok {
        match => {
          "[docker_json][log]" => "%{TIMESTAMP_ISO8601:[docker][log][datetime]} %{WORD:[docker][log][level]} %{GREEDYDATA:[docker][log][message]}"
        }
      }
      date {
        match => [ "[docker_json][time]", "ISO8601" ]
        target => "@timestamp"
      }
      mutate {
        add_field => { "[docker][log][type]" => "%{[docker_json][stream]}" }
        remove_field => ["message", "docker_json", "prospector", "input"]
      }
    }
  }
  else if [agent][type] == "heartbeat" {
    mutate {
      add_tag => [ "heartbeat_data" ]
      add_field => { "[@metadata][beat]" => "heartbeat" }
    }
  }
}

output {
  if [@metadata][beat] == "heartbeat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      action => "create"
      data_stream => "true"
      data_stream_type => "logs"
      data_stream_dataset => "heartbeat"
      data_stream_namespace => "default"
    }
  } else if [@metadata][beat] == "filebeat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      data_stream => "true"
      data_stream_type => "logs"
      data_stream_dataset => "filebeat"
      data_stream_namespace => "default"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "%{[@metadata][beat]}-%{[@metadata][version]}"
      action => "create"
    }
  }
}