version: '3.8'
services:
  redis:
    image: sloopstash/redis:v4.0.9
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data:/opt/redis/data
      - redis-log:/opt/redis/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/redis/${CRM_REDIS_VERSION}/conf/supervisor.ini:/opt/redis/system/supervisor.ini
      - ${HOME_DIR}/workload/redis/${CRM_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/server.conf
    networks:
      common:
        ipv4_address: ${CRM_REDIS_IP}
  app:
    image: sloopstash/python:v2.7
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    environment:
      - STATIC_ENDPOINT=http://app-static.crm.${EXTERNAL_DOMAIN}:${CRM_NGINX_PORT}
    volumes:
      - ${CRM_APP_SOURCE}:/opt/app/source
      - app-log:/opt/app/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/_stack/crm/app/conf/supervisor.ini:/opt/app/system/supervisor.ini
    depends_on:
      - redis
    networks:
      common:
        ipv4_address: ${CRM_APP_IP}
  nginx:
    image: sloopstash/nginx:v1.14.0
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    ports:
      - "${CRM_NGINX_PORT}:80"
    volumes:
      - ${CRM_APP_SOURCE}:/opt/app/source
      - nginx-log:/opt/nginx/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/nginx/${CRM_NGINX_VERSION}/conf/supervisor.ini:/opt/nginx/system/supervisor.ini
      - ${HOME_DIR}/workload/nginx/${CRM_NGINX_VERSION}/conf/server.conf:/opt/nginx/conf/server.conf
      - ${HOME_DIR}/_stack/crm/nginx/conf/app.conf:/opt/nginx/conf/app.conf
    depends_on:
      - app
    networks:
      common:
        ipv4_address: ${CRM_NGINX_IP}
volumes:
  redis-data:
    driver: local
  redis-log:
    driver: local
  app-log:
    driver: local
  nginx-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CRM_NETWORK}
