version: '3.8'
services:
  mongo-db:
    image: sloopstash/mongo-db:v4.4.4
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-data:/opt/mongo-db/data
      - mongo-db-log:/opt/mongo-db/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/mongo-db/${CTM_MONGO_DB_VERSION}/conf/supervisor.ini:/opt/mongo-db/system/supervisor.ini
      - ${HOME_DIR}/workload/mongo-db/${CTM_MONGO_DB_VERSION}/conf/server.conf:/opt/mongo-db/conf/server.conf
    networks:
      common:
        ipv4_address: ${CTM_MONGO_DB_IP}
  app:
    image: sloopstash/node-js:v17.7.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    environment:
      - STATIC_ENDPOINT=http://app-static.ctm.${EXTERNAL_DOMAIN}:${CTM_NGINX_PORT}
    volumes:
      - ${CTM_APP_SOURCE_FRONTEND}:/opt/app/source/view
      - ${CTM_APP_SOURCE_BACKEND}:/opt/app/source
      - app-log:/opt/app/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/_stack/ctm/app/conf/supervisor.ini:/opt/app/system/supervisor.ini
    depends_on:
      - mongo-db
    ports:
      - "${CTM_APP_HOST_PORT}:${CTM_APP_CONTAINER_PORT}" 
    networks:
      common:
        ipv4_address: ${CTM_APP_IP}
  nginx:
    image: sloopstash/nginx:v1.14.0
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    ports:
      - "${CTM_NGINX_PORT}:${CTM_NGINX_DEFAULT_PORT}"
    volumes:
      - ${CTM_APP_SOURCE_FRONTEND}:/opt/app/source/view
      - nginx-log:/opt/nginx/log
      - ${HOME_DIR}/workload/supervisor/conf/server.conf:/etc/supervisord.conf
      - ${HOME_DIR}/workload/nginx/${CTM_NGINX_VERSION}/conf/supervisor.ini:/opt/nginx/system/supervisor.ini
      - ${HOME_DIR}/workload/nginx/${CTM_NGINX_VERSION}/conf/server.conf:/opt/nginx/conf/server.conf
      - ${HOME_DIR}/_stack/ctm/nginx/conf/app.conf:/opt/nginx/conf/app.conf
    depends_on:
      - app
    networks:
      common:
        ipv4_address: ${CTM_NGINX_IP}
volumes:
  mongo-db-data:
    driver: local
  mongo-db-log:
    driver: local
  app-log:
    driver: local
  nginx-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CTM_NETWORK}
